services:
  - type: web
    name: mi-proyecto-flask
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    region: oregon
